filter:
  paths:
    - 'src/*'

checks:
  javascript: true

tools:
  external_code_coverage: false

build:
  nodes:
    coverage:
      tests:
        override:
          - js-scrutinizer-run
          - command: npm test
            coverage:
              file: tests/coverage/clover.xml
              format: clover